name: artsteez
favicon: null
layout_spectrum: 0.42942892108112574
typography_spectrum: 0.6531889901962131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.007328831357881427
  lightness: 0.23537674266844988
  saturation: 0.6658125657122582
  rhythmicContrast: 0.4748420175164938
purpose: []
